### ISSUE TITLE
v4 issues - can't import

### ISSUE THREAD

**Issue by rwrz** [eko/gocache#186] opened 2022-12-03 16:10 UTC
I'm trying to import the v4 but I can't, this error show up:

```
go: finding module for package github.com/eko/gocache/v4/lib
reallifeglobal.com/common/cache imports
	github.com/eko/gocache/v4/lib: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache/v4/lib
```

To reproduce:

- create a new project
- try to follow installation steps

**Comment by fbozzo-sniptech** [comment] 2022-12-03 17:32
Same here :(

**Comment by eko** [comment] 2022-12-03 20:03
Hi,

Thank you and sorry about that.

Imports should now be functional by replacing `github.com/eko/gocache/v4/lib` with `github.com/eko/gocache/lib/v4`.

Indeed, the version number of a Go module should be a suffix of the module name.

```bash
$ go get github.com/eko/gocache/lib/v4@v4.1.1
```

**Comment by ddliu** [comment] 2022-12-04 03:47
Same here with `go mod tidy` error, to reproduce:

```
package main

import (
	"github.com/eko/gocache/lib/v4/marshaler"
)

func main() {
	marshaler.New(nil)
}
```

Error message when run `go mod tidy`:

```
go mod tidy
go: finding module for package github.com/eko/gocache/v4/lib/metrics
go: finding module for package github.com/eko/gocache/v4/lib/cache
go: finding module for package github.com/eko/gocache/v4/lib/codec
go: finding module for package github.com/eko/gocache/v4/lib/store
app imports
        github.com/eko/gocache/lib/v4/marshaler tested by
        github.com/eko/gocache/lib/v4/marshaler.test imports
        github.com/eko/gocache/v4/lib/cache: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache/v4/lib/cache
app imports
        github.com/eko/gocache/lib/v4/marshaler tested by
        github.com/eko/gocache/lib/v4/marshaler.test imports
        github.com/eko/gocache/v4/lib/store: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache/v4/lib/store
app imports
        github.com/eko/gocache/lib/v4/marshaler imports
        github.com/eko/gocache/lib/v4/cache tested by
        github.com/eko/gocache/lib/v4/cache.test imports
        github.com/eko/gocache/v4/lib/codec: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache/v4/lib/codec
app imports
        github.com/eko/gocache/lib/v4/marshaler imports
        github.com/eko/gocache/lib/v4/cache tested by
        github.com/eko/gocache/lib/v4/cache.test imports
        github.com/eko/gocache/v4/lib/metrics: module github.com/eko/gocache@latest found (v1.2.0), but does not contain package github.com/eko/gocache/v4/lib/metrics
```

**Comment by ddliu** [comment] 2022-12-04 09:57
`v4.1.2` works for me, thanks.

**Comment by eko** [comment] 2022-12-04 11:14
Cool, thanks to you all for your quick feedback.

I close this issue but feel free to reopen if you still have any issue.

**Closed by eko** 2022-12-04 11:14 UTC
