### ISSUE TITLE
Support for Hazelcast cache 

### ISSUE THREAD

**Issue by smsufyian** [eko/gocache#33] opened 2020-03-03 20:48 UTC
Like other cache support for example redis , memcache . Tool should be extended to provide support for hazelcast.

**Comment by s-m-sufyian** [comment] 2020-03-03 20:48
@eko I am willing to add support for hazelcase issue

**Comment by eko** [comment] 2021-05-28 17:03
Hi @smsufyian,

I will be interested if you could add support for Hazelcast.

Closing this issue because this is a duplicate of https://github.com/eko/gocache/issues/6, please continue on this thread.

Thank you

**Closed by eko** 2021-05-28 17:03 UTC
